### ISSUE TITLE
SecurityRAT web does not redirect to CAS

### ISSUE THREAD

**Issue by dalini** [SecurityRAT/SecurityRAT#1]
we try to get the dev version running - but weren't very successful so far.
CAS is up and running and looks as it is working but the securityRAT itself does not redirect to CAS - it is all in one vm and the config looks fine - but if one connects to the port the connection is just closed instead of redirected to the cas system:

cas:
    casLoginUrl: http://localhost:8080/cas #Change to the URL your CAS server listens on
    callbackUrl: http://localhost:9000/callback #Change to the correct URL of SecurityRAT

root@SecurityRAT02:~$ telnet localhost 9000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1
Connection closed by foreign host.
root@SecurityRAT02:~$

**Comment by AresSec** [comment]
Hi Ives,
is your cas running under: http://localhost:8080/cas ? So you can actually call that url and are able to sign-in with your configured user?
Have you configured your self-signed dev certificate according the Readme.md?:
enable TLS for spring boot if you don't use a separate web server:

    e.g. generate a self-signed certificate in the root directory of SecurityRAT: keytool -genkey -alias tomcat -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
    add the following lines into application-dev.yml:

server:
  ssl:
    key-store: keystore.p12
    key-store-password: mypassword
    keyStoreType: PKCS12
    keyAlias: tomcat

    in the same file, set the CAS callback url to https:// instead of http://

Regards,
René

**Comment by s1l3nt-cr0w** [comment]
Hi René,

thank you for your quick reply. 
To your question:
is your cas running under: http://localhost:8080/cas ? YES
So you can actually call that url and are able to sign-in with your configured user? YES
Have you configured your self-signed dev certificate according the Readme.md?: YES

Look the screenshot:
![cas_login](https://cloud.githubusercontent.com/assets/19819836/16611518/1c882b0c-4362-11e6-93b5-ac7644836a63.png)

Is the password "mypassword" compelling for SecurityRAT because hardcoded? Because that's different.

best regards,
cr0w

**Comment by dkefer** [comment]
Hi cr0w,

have you configured SecurityRAT for http or https? You're writing that you've generated and set your certificate, but in your config file is callbackUrl set to http:// and you're calling SecurityRAT with telnet which obviously won't work with TLS. You also need to set your password for the keystore file (the one you used for generation of the certificate). 

What does the console output say?

Cheers,
Daniel

**Comment by s1l3nt-cr0w** [comment]
Hi Daniel,

sorry, auf Deutsch um Missverständisse auszuschließen. Habe es noch mal überprüft und alles in https:// geändert und die Ports angepasst.
Eintragungen in  application-dev.yml:
cas:
    casLoginUrl: https://localhost:8443/cas #Change to the URL your CAS server listens on
    callbackUrl: https://localhost:9000/callback #Change to the correct URL of SecurityRAT

Anmeldung erfolgreich:
![cas_https](https://cloud.githubusercontent.com/assets/19819836/16614467/b1e73936-4371-11e6-92ee-c12df86dff35.png)

nach der Anmeldung bekomme ich jetzt allerdings folgendes angezeigt:
![cas_callback](https://cloud.githubusercontent.com/assets/19819836/16615085/8a299882-4374-11e6-8ca6-6456737d7138.png)

Konsole:
$ sudo mvn spring-boot:run
[INFO] org.appsec.securityRAT.Application - Access URLs:
----------------------------------------------------------
        Local:          http://127.0.0.1:9000
        External:       http://10.0.0.5:9000
----------------------------------------------------------
[ERROR] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No name matching localhost found
[ERROR] org.apache.velocity - ResourceManager : unable to find resource 'error.vm' in any resource loader.

Warum er da http:// nimmt ist mir schleierhaft.

Grüße
Cr0w

**Comment by dkefer** [comment]
Hi Cr0w,

I'll answer in English so that everyone running into the same problem can understand the solution. If you don't understand anything, just ping me. 

The login flow with CAS is the following.
1. You point your browser to SecurityRAT. If you come without a valid session id, you get redirected to CAS Server (casLoginUrl from the config file).
2. If you haven't logged in to the CAS server yet, you will be asked for your credentials. If you have a valid CAS session, you will get redirected back to SecurityRAT directly (to callbackUrl from the config file). This redirect contains "ticket" parameter with a one time token (you can see this in your screenshot).
3. SecurityRAT takes the "ticket" parameter value and tries to exchange this for user details itself at the CAS Server. 

Judging from your screenshot and your console output, I think that SecurityRAT just can't validate the certificate of your CAS server in step 3 and that's why the handshake fails, the redirect itself works. 

You have two options how to address that:
1. Add the CAS server certificate to the truststore of SecurityRAT. By default, that would be the cacerts file. For a tutorial how to do it, look e.g. here: http://stackoverflow.com/questions/11617210/how-to-properly-import-a-selfsigned-certificate-into-java-keystore-that-is-avail
2. Switch your CAS server to listen on plain http and configure casLoginUrl with http as well (SecurityRAT needs to stay on https, otherwise CAS will refuse to do the redirect back to SecurityRAT). Of course, this is neither elegant nor secure, but probably sufficient if you just want to play around on localhost. 

Let me know if this helped.

Cheers, 
Daniel

**Comment by s1l3nt-cr0w** [comment]
runs now with option 2 - to get it working in a test environment - this is sufficient for now

**Comment by dkefer** [comment]
Cool, closing here.
