### ISSUE TITLE
Motivation and More Information columns disappears after some minutes

### ISSUE THREAD

**Issue by masooh** [SecurityRAT/SecurityRAT#111]
Steps to reproduce:

1. Open existing SSDLC project in SecurityRAT
1. Start the update process
1. Wait some minutes

Then Motivation and More Information columns are removed.
The columns cannot be shown with clicking on the "Hide-Information" eye icon.

**Comment by AresSec** [comment]
Hi @masooh ,
sorry for the late reply. I tried to reproduce it, but on my instance everything works fine. So to understand it:

- You've an existing requirement set and created a new artifact
- You've modified the current requirement set, e.g. a requirement skeleton
- You've Imported the previous created artifcat and pushed the update button
- After a couple of minutes the motivation and more information columns disappeared for you?

Which version do you use of SecurityRAT?
René

**Comment by rylyade1** [comment]
Hi @masooh, 
I couldn't reproduce this issue as well. Consequently, I will close it. In case you come across this problem again in the future, just report it in a new issue.
Many thanks

**Comment by masooh** [comment]
Hi @rylyade1,
sorry for late answer. Issue is still relevant.

So here more details:

1. Opened existing requirement set
1. Clicked on Update
1. Accepted first
1. Denied second
1. Accepted third
1. Waiting
1. More Information and Motivation disappears

Version v1.7.7
![Screenshot_security-rat-111](https://user-images.githubusercontent.com/1352902/58250492-cca25080-7d61-11e9-8641-beb40a38d03d.png)

**Comment by rylyade1** [comment]
Thank you @masooh for the input, I was able to reproduce it. I would just reopen the ticket.

**Comment by rylyade1** [comment]
It turns out this was caused by the save to local storage feature which runs every minutes and saves the changed state of the requirement set (in this case when the user for example updates one requirement). During this process the property which contains the **diffs** (content highlighting the differences in the requirement) was deleted, hence causing the disappearance.

**Resolution**
- I deactivated this save to local storage feature when the user is updating requirements as this doesn't make much sense.
- Also a copy of the requirement set object is used.
