### ISSUE TITLE
Some content optional columns causing incorrect artifact view

### ISSUE THREAD

**Issue by ScriptGod1337** [SecurityRAT/SecurityRAT#126]
Some predefined content for optional columns are causing incorrect content in the artifact definition view
1. having an optional column
2. setting content for this optional column
3. having this requirement in the artifact creating view
-> selection checkbox is missing

e.g. of a content of the optional column
> auth.inMemoryAuthentication().passwordEncoder(new BCryptPasswordEncoder(10))
     .withUser("waiter").password("$2a$10$n5UZipMzWmYB18AWbyZES.t9FDJP/9OFp8hKI1rzol6gn/2hVZYE2").roles("Waiter")
     and().withUser("user0").password("$2a$10$atp6JC.anPKGhNwc1dEK0OQFzPr3/5moIm7bF1i2yBHXFKpA7YMb2").roles("Customer"); 
results in this content in the artifact view
![SecurityRat missing,checkbox](https://user-images.githubusercontent.com/53829529/64692232-e1336180-d494-11e9-9907-fc8f489c06a1.png)

**Comment by rylyade1** [comment]
Hi @ScriptGod1337 

thanks for reporting this behavior. This is probably caused by the long string without spacing which makes the table body in this requirements view horizontally scrollable. You need to scroll to the right to see the selection checkbox.

In case you wish to add block code snippet, you can do it via markdown. You can view this [markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)  for guidance. I am closing this issue.
