### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by firefligher** [SecurityRAT/SecurityRAT#135]
Hi,
i just discovered that it is not possible to create or update (at least) _Optional Column Content_ entries that contain the right arrow character (→, U+2192).

**What I tried:**
- Creating a new _Optional Column Content_ entry using the REST interface. I got a _500 Internal Server Error_ as response state.
- Updating an existing _Optional Column Content_ entry using the graphical Web-UI. This results in a red message box with the following text: `could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement`

I did not check, if this error also applies for the other entity types.

**Comment by rylyade1** [comment]
Hi @firefligher 
the issue arose because the character set supported by the all database tables is _mysql utf-8_ which doesn't allow all unicode characters. The desired encoding should be _utf8mb4_.
You can change the encoding of the _OPTIONCOLUMNCONTENT_ table with the following command:

 `ALTER TABLE OPTCOLUMNCONTENT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

More information is available [here](https://mathiasbynens.be/notes/mysql-utf8mb4).

**Comment by firefligher** [comment]
Nice, that did it. Thanks.
