### ISSUE TITLE
CAS as authentication layer

### ISSUE THREAD

**Issue by dalini** [SecurityRAT/SecurityRAT#3]
Are there any plans and timelines to get rid of CAS?

**Comment by dkefer** [comment]
There is actually way more than plans and timelines ;)

CAS has been optional since 1.1.0, versino 1.2.0 then brought some enhancements (you can choose whether you allow users to register themselves). Just yesterday, 1.3.0 was pushed


CAS has been optional since 1.1.0, versino 1.2.0 then brought some enhancements (you can choose whether you allow users to register themselves). Just yesterday, 1.3.0 was pushed. Feel free to give it a try and give us feedback! :)

**Comment by dkefer** [comment]
I guess the question has been answered -> closing here.
